### ISSUE TITLE
StartsWith is not a function

### ISSUE THREAD

**Issue by noqcks** [noqcks/generated#9]
```
this.lines[0].StartsWith is not a function
at Generated.isGeneratedGrammarkit (/var/task/node_modules/@noqcks/generated/lib/generated.js:197:26)
```

I'm seeing this in the pull-request-size github bot logs. 

EDIT: this was fixed by e635af08f24fa840080b83dd2c274cf155045c7c

**Comment by noqcks** [comment]
as well
```
Cannot read property 'toString' of undefined
at new Generated (/var/task/node_modules/@noqcks/generated/lib/generated.js:8:23)
```
